server:
  port: 8083

spring:
  application:
    name: asset-onboarding-service
  datasource:
    url: jdbc:mysql://localhost:3306/vdms
    username: root
    password: mypass123
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

services:
  asset-service:
    base-url: lb://asset-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
